{
 "title": "Logging Dashboard",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Fluent-bit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentbit.*\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentd.*\",pod!~\".*config.*\"})"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluentd output emit/s by Plugin",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count[1m])",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_retries_total[1m])",
     "legendFormat": "Retries {{ pod }}"
    },
    {
     "expr": "rate(fluentbit_output_retries_failed_total[1m])",
     "legendFormat": "Failed {{ pod }}"
    }
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count[1m]))",
     "legendFormat": "Retry rate"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Fluentd output buffer size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  }
 ]
}