// Code generated by "gen-kindstubs -parentpath=github.com/caos/orbiter/internal/kinds -versions=v0 -kind=nodeagent.caos.ch/NodeAgent from file gen.go"; DO NOT EDIT.

package v0

import (
	"errors"

	"github.com/caos/orbiter/internal/core/operator/orbiter"
	"github.com/caos/orbiter/internal/kinds/nodeagent/model"
)

var build func(map[string]interface{}, *orbiter.Secrets, interface{}) (model.UserSpec, func(model.Config) ([]orbiter.Assembler, error))

func Build(spec map[string]interface{}, secrets *orbiter.Secrets, dependant interface{}) (model.UserSpec, func(cfg model.Config) ([]orbiter.Assembler, error)) {
	if build != nil {
		return build(spec, secrets, dependant)
	}
	return model.UserSpec{}, func(_ model.Config) ([]orbiter.Assembler, error) {
		return nil, errors.New("Version v0 for kind nodeagent.caos.ch/NodeAgent is not yet supported")
	}
}
