{
 "title": "Health / ZITADEL",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "store",
    "query": "label_values(caos_cr_capacity_store_ryg, store)"
   },
   {
    "name": "instance",
    "query": "label_values(caos_cr_replicas_nodes_ryg, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CockroadDB Runtime Cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_cluster_ryg)"
    }
   ]
  },
  {
   "title": "CockroadDB Runtime Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_instances_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Runtime Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_instances_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Runtime Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_instances_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_nodes_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_nodes_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Instance $instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_nodes_ryg{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "repeat": "store",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_stores_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_stores_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_stores_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Cluster Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_cluster_ryg)"
    }
   ]
  },
  {
   "title": "CockroadDB Disk Space Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "repeat": "store",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_store_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Disk Space Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_store_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Disk Space Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_store_ryg{store=\"$store\"})"
    }
   ]
  }
 ]
}