{
 "title": "Health / ZITADEL Details",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "store",
    "query": "label_values(caos_cr_capacity_store_ryg, store)"
   },
   {
    "name": "pod",
    "query": "label_values(caos_cr_replicas_nodes_ryg, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unready Pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dist_kube_statefulset_replicas{controller=\"cockroachdb\",namespace=\"caos-zitadel\"} - dist_kube_statefulset_status_replicas_current{controller=\"cockroachdb\",namespace=\"caos-zitadel\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "dist_kube_deployment_status_replicas{controller=\"zitadel\",namespace=\"caos-zitadel\"} - dist_kube_deployment_spec_replicas{controller=\"zitadel\",namespace=\"caos-zitadel\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "dist_kube_deployment_status_replicas{controller=\"zitadel-operator\",namespace=\"caos-system\"} - dist_kube_deployment_spec_replicas{controller=\"zitadel-operator\",namespace=\"caos-system\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cr_runtime_high_open_fd_count", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Flapping Pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cr_runtime_pod_flapping", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Version Mismatches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - cr_runtime_version_mismatches",
     "legendFormat": "overall count"
    }
   ]
  },
  {
   "title": "Clock offsets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "clock_offset_meannanos", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Certificate Expiration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "(security_certificate_expiration_ca{job=\"cockroachdb\"} - time()) / 86400",
     "legendFormat": "CA {{pod}}"
    },
    {
     "expr": "(security_certificate_expiration_node{job=\"cockroachdb\"} - time()) / 86400",
     "legendFormat": "Node {{pod}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_slow_latch{job=\"cockroachdb\"}",
     "legendFormat": "latch store {{store}}"
    },
    {
     "expr": "requests_slow_lease{job=\"cockroachdb\"}",
     "legendFormat": "lease store {{store}}"
    },
    {
     "expr": "requests_slow_raft{job=\"cockroachdb\"}",
     "legendFormat": "raft store {{store}}"
    }
   ]
  }
 ]
}