{
 "title": "Zitadel Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http server duration sum",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "http_server_duration_sum", "legendFormat": "{{http_host}} - {{instance}}" }
   ]
  },
  {
   "title": "http server duration bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "http_server_duration_bucket", "legendFormat": "{{http_host}} - {{instance}}" }
   ]
  },
  {
   "title": "http server duration count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "http_server_duration_count" }
   ]
  },
  {
   "title": "http server request content length",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_request_content_length",
     "legendFormat": "{{http_host}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server response content length",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_response_content_length",
     "legendFormat": "{{http_host}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server return code 200 counter",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_return_code_counter{return_code=\"200\"}",
     "legendFormat": "{{method}} - {{uri}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server return code 302 counter",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_return_code_counter{return_code=\"302\"}",
     "legendFormat": "{{method}} - {{uri}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server return code 400 counter",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_return_code_counter{return_code=\"400\"}",
     "legendFormat": "{{method}} - {{uri}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server request count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_request_count",
     "legendFormat": "{{method}} - {{uri}} - {{instance}}"
    }
   ]
  },
  {
   "title": "http server total request count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "http_server_total_request_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "grpc sum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "grpc status 200 count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_grpc_status_code{return_code=\"200\"})",
     "legendFormat": "{{grpc_method}} -{{instance}} "
    }
   ]
  },
  {
   "title": "grpc status 401 count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_grpc_status_code{return_code=\"401\"})",
     "legendFormat": "{{grpc_method}} -{{instance}} "
    }
   ]
  },
  {
   "title": "grpc status 403 count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_grpc_status_code{return_code=\"403\"})",
     "legendFormat": "{{grpc_method}} -{{instance}} "
    }
   ]
  },
  {
   "title": "grpc status 500 count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_grpc_status_code{return_code=\"500\"})",
     "legendFormat": "{{grpc_method}} -{{instance}} "
    }
   ]
  },
  {
   "title": "grpc server request counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_request_counter)"
    }
   ]
  },
  {
   "title": "grpc total request counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "grpc_server_total_request_counter",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "zitadel spooler div", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "ALL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zitadel_active_session_counter" }
   ]
  },
  {
   "title": "adminapi",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds{database=\"adminapi\"}"
    }
   ]
  },
  {
   "title": "auth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds{database=\"auth\"}"
    }
   ]
  },
  {
   "title": "authz",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds{database=\"authz\"}"
    }
   ]
  },
  {
   "title": "management",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds{database=\"management\"}"
    }
   ]
  },
  {
   "title": "notification",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zitadel_spooler_div_milliseconds{database=\"notification\"}"
    }
   ]
  }
 ]
}