// Code generated by "stringer -type=drainReason"; DO NOT EDIT.

package drainreason

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Updating-0]
	_ = x[Rebooting-1]
	_ = x[Deleting-2]
}

const _drainReason_name = "updatingrebootingdeleting"

var _drainReason_index = [...]uint8{0, 8, 17, 25}

func (i DrainReason) String() string {
	if i < 0 || i >= DrainReason(len(_drainReason_index)-1) {
		return "drainReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _drainReason_name[_drainReason_index[i]:_drainReason_index[i+1]]
}
