// Code generated by goderive DO NOT EDIT.

package kubernetes

import (
	v1 "k8s.io/api/core/v1"
)

// deriveFilter returns a list of all items in the list that matches the predicate.
func deriveFilter(predicate func(v1.Pod) bool, list []v1.Pod) []v1.Pod {
	j := 0
	for i, elem := range list {
		if predicate(elem) {
			if i != j {
				list[j] = list[i]
			}
			j++
		}
	}
	return list[:j]
}
