// Code generated by goderive DO NOT EDIT.

package adapter

import (
	infra "github.com/caos/orbiter/internal/kinds/clusters/core/infra"
)

// deriveFilter returns a list of all items in the list that matches the predicate.
func deriveFilter(predicate func(infra.Compute) bool, list []infra.Compute) []infra.Compute {
	j := 0
	for i, elem := range list {
		if predicate(elem) {
			if i != j {
				list[j] = list[i]
			}
			j++
		}
	}
	return list[:j]
}
