{
 "title": "Boom",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Boom status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(boom_crd_format_gyr) * avg(boom_current_state_write_gyr) * avg(boom_git_gyr) * avg(boom_current_state_read_gyr)"
    }
   ]
  },
  { "title": "Git", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Git connection status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(boom_git_gyr)" }
   ]
  },
  {
   "title": "Total git clones",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(boom_git_clone)" }
   ]
  },
  {
   "title": "Git clone Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_git_clone{result=\"success\"}[1m])",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Git clone Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_git_clone{result=\"failure\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "CRD Format", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CRD format status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(boom_crd_format_gyr)" }
   ]
  },
  {
   "title": "Total crd format",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(boom_crd_format)" }
   ]
  },
  {
   "title": "CRD format Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_crd_format{result=\"success\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "CRD format Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_crd_format{result=\"failure\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "Current state read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Current state read status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(boom_current_state_read_gyr)"
    }
   ]
  },
  {
   "title": "Total current state read",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(boom_current_state_read)" }
   ]
  },
  {
   "title": "Current state read Succes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_current_state_read{result=\"success\"}[1m])",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Current state write Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(delta(boom_current_state_write{result=\"failure\"}[1m]),0)",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "Current state write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Current state write status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(boom_current_state_write_gyr)"
    }
   ]
  },
  {
   "title": "Total current state write",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(boom_current_state_write)" }
   ]
  },
  {
   "title": "Current state write Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(boom_current_state_write{result=\"success\"}[1m])",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Current state read Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(delta(boom_current_state_read{result=\"failure\"}[1m]),0)"
    }
   ]
  },
  { "title": "Reconciling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Application reconciling status",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(boom_reconciling_application)"
    }
   ]
  },
  {
   "title": "Total reconciled bundles",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(boom_reconciling_bundle)" }
   ]
  },
  {
   "title": "Bundle reconciling Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(boom_reconciling_bundle{result=\"success\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Bundle reconciling Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(delta(boom_reconciling_bundle{result=\"failure\"}[1m])),0)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Total reconciled applications",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(boom_reconciling_application)"
    }
   ]
  },
  {
   "title": "Application reconciling Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(boom_reconciling_application{result=\"success\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Application reconciling Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum(delta(boom_reconciling_application{result=\"failure\"}[1m])),0)",
     "legendFormat": "Failure"
    }
   ]
  }
 ]
}