// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/caos/ingestion/internal/src/proto/ingestion.proto.gen

package ingestion

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventsRequest struct {
	Orb                  string          `protobuf:"bytes,1,opt,name=orb,proto3" json:"orb,omitempty"`
	Events               []*EventRequest `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da9aaf13f90b55ec, []int{0}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetOrb() string {
	if m != nil {
		return m.Orb
	}
	return ""
}

func (m *EventsRequest) GetEvents() []*EventRequest {
	if m != nil {
		return m.Events
	}
	return nil
}

type EventRequest struct {
	CreationDate         *timestamp.Timestamp `protobuf:"bytes,1,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Data                 *_struct.Struct      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da9aaf13f90b55ec, []int{1}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetCreationDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *EventRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *EventRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*EventsRequest)(nil), "caos.ingestion.api.v1.EventsRequest")
	proto.RegisterType((*EventRequest)(nil), "caos.ingestion.api.v1.EventRequest")
}

func init() {
	proto.RegisterFile("github.com/caos/ingestion/internal/src/proto/ingestion.proto.gen", fileDescriptor_da9aaf13f90b55ec)
}

var fileDescriptor_da9aaf13f90b55ec = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0xdb, 0x7f, 0xff, 0xb8, 0x6d, 0xa1, 0x2c, 0xa8, 0x21, 0x0a, 0x96, 0xea, 0xa1,
	0x28, 0x6c, 0xb0, 0x1e, 0x44, 0x3c, 0x28, 0x62, 0x41, 0x3d, 0x49, 0xea, 0xc9, 0x83, 0xb2, 0x49,
	0xc7, 0x74, 0xa1, 0xc9, 0xc6, 0xdd, 0x49, 0xa1, 0x3e, 0x85, 0xcf, 0xe6, 0x13, 0x49, 0x36, 0x89,
	0x95, 0xd4, 0x0a, 0xde, 0x26, 0xf9, 0xe6, 0xf7, 0xe5, 0x9b, 0xc9, 0x90, 0xcb, 0x50, 0xe0, 0x34,
	0xf5, 0x59, 0x20, 0x23, 0x37, 0xe0, 0x52, 0xbb, 0x22, 0x0e, 0x41, 0xa3, 0x90, 0xb1, 0x2b, 0x62,
	0x04, 0x15, 0xf3, 0x99, 0xab, 0x55, 0xe0, 0x26, 0x4a, 0xa2, 0x5c, 0x8a, 0xcc, 0x3c, 0xb3, 0x10,
	0x62, 0xba, 0x99, 0x61, 0x6c, 0xa9, 0xf0, 0x44, 0xb0, 0xf9, 0xb1, 0xb3, 0x17, 0x4a, 0x19, 0xce,
	0x20, 0x07, 0xfd, 0xf4, 0xc5, 0x45, 0x11, 0x81, 0x46, 0x1e, 0x25, 0x39, 0xeb, 0xec, 0x56, 0x1b,
	0x34, 0xaa, 0x34, 0xc0, 0x42, 0xdd, 0xa9, 0xaa, 0x10, 0x25, 0xb8, 0xc8, 0xc5, 0xfe, 0x13, 0xe9,
	0x8c, 0xe6, 0x10, 0xa3, 0xf6, 0xe0, 0x35, 0x05, 0x8d, 0xb4, 0x4b, 0xea, 0x52, 0xf9, 0xb6, 0xd5,
	0xb3, 0x06, 0x1b, 0x5e, 0x56, 0xd2, 0x73, 0xd2, 0x04, 0xd3, 0x62, 0xd7, 0x7a, 0xf5, 0x41, 0x6b,
	0xb8, 0xcf, 0x7e, 0x8c, 0xc9, 0x8c, 0x4f, 0x61, 0xe3, 0x15, 0x48, 0xff, 0xdd, 0x22, 0xed, 0xef,
	0x02, 0xbd, 0x20, 0x9d, 0x40, 0x01, 0xcf, 0xc0, 0xe7, 0x09, 0x47, 0x30, 0x5f, 0x6a, 0x0d, 0x1d,
	0x96, 0xa7, 0x64, 0x65, 0x4a, 0xf6, 0x50, 0x0e, 0xe9, 0xb5, 0x4b, 0xe0, 0x9a, 0x23, 0xd0, 0x23,
	0xd2, 0x98, 0x70, 0xe4, 0x76, 0xcd, 0x70, 0xdb, 0x2b, 0xdc, 0xd8, 0xcc, 0xee, 0x99, 0x26, 0x4a,
	0x49, 0x03, 0x17, 0x09, 0xd8, 0x75, 0x33, 0x8e, 0xa9, 0x87, 0x1f, 0x16, 0xe9, 0xde, 0x96, 0xe1,
	0xc7, 0xa0, 0xe6, 0x22, 0x00, 0x7a, 0x46, 0xfe, 0xdf, 0x00, 0x9f, 0xe1, 0xf4, 0x8d, 0x6e, 0xad,
	0x58, 0x8e, 0xb2, 0x85, 0x39, 0x6b, 0xde, 0xd3, 0x53, 0xf2, 0xcf, 0x03, 0x3e, 0x59, 0xfc, 0x19,
	0xbc, 0x23, 0xe4, 0x3e, 0xd5, 0xd3, 0x7c, 0xff, 0xf4, 0xe0, 0xb7, 0xb5, 0x96, 0xbf, 0x67, 0x9d,
	0xd7, 0xd5, 0xe1, 0xe3, 0xa0, 0x7a, 0x7e, 0x52, 0xf9, 0xe6, 0x08, 0x8b, 0xd3, 0xfb, 0x32, 0xf6,
	0x9b, 0x86, 0x3d, 0xf9, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x94, 0x6d, 0x95, 0xe1, 0xb1, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IngestionServiceClient is the client API for IngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IngestionServiceClient interface {
	// Healthz returns status OK as soon as the service started
	Healthz(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Ready returns status OK as soon as all dependent services are available
	Ready(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	PushEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type ingestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionServiceClient(cc grpc.ClientConnInterface) IngestionServiceClient {
	return &ingestionServiceClient{cc}
}

func (c *ingestionServiceClient) Healthz(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/caos.ingestion.api.v1.IngestionService/Healthz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionServiceClient) Ready(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/caos.ingestion.api.v1.IngestionService/Ready", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionServiceClient) PushEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/caos.ingestion.api.v1.IngestionService/PushEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestionServiceServer is the server API for IngestionService service.
type IngestionServiceServer interface {
	// Healthz returns status OK as soon as the service started
	Healthz(context.Context, *empty.Empty) (*empty.Empty, error)
	// Ready returns status OK as soon as all dependent services are available
	Ready(context.Context, *empty.Empty) (*empty.Empty, error)
	PushEvents(context.Context, *EventsRequest) (*empty.Empty, error)
}

// UnimplementedIngestionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIngestionServiceServer struct {
}

func (*UnimplementedIngestionServiceServer) Healthz(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (*UnimplementedIngestionServiceServer) Ready(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (*UnimplementedIngestionServiceServer) PushEvents(ctx context.Context, req *EventsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushEvents not implemented")
}

func RegisterIngestionServiceServer(s *grpc.Server, srv IngestionServiceServer) {
	s.RegisterService(&_IngestionService_serviceDesc, srv)
}

func _IngestionService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caos.ingestion.api.v1.IngestionService/Healthz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).Healthz(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caos.ingestion.api.v1.IngestionService/Ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).Ready(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionService_PushEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).PushEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caos.ingestion.api.v1.IngestionService/PushEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).PushEvents(ctx, req.(*EventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IngestionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "caos.ingestion.api.v1.IngestionService",
	HandlerType: (*IngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _IngestionService_Healthz_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _IngestionService_Ready_Handler,
		},
		{
			MethodName: "PushEvents",
			Handler:    _IngestionService_PushEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/caos/ingestion/internal/src/proto/ingestion.proto.gen",
}
