server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: ${E2E_LOKI_PUSH_URL}

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      e2e_test: true
      __path__: /var/log/*.log
