server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://4270:eyJrIjoiNjY4MmI3NzcyODhkOWJkMDQxOWJlZmY0NWRmNTdjMDQ4Y2EyMjRiNSIsIm4iOiJlMmUgdGVzdCBzdGF0dXMiLCJpZCI6MzYxNzg1fQ==@logs-prod-us-central1.grafana.net/api/prom/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
