// Code generated by "stringer -type=Action"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Insert-0]
	_ = x[Delete-1]
	_ = x[Add-2]
	_ = x[Remove-3]
}

const _Action_name = "InsertDeleteAddRemove"

var _Action_index = [...]uint8{0, 6, 12, 15, 21}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
