{
 "title": "Health / Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"caos_remote_(node-exporter|systemd-exporter)\"}, instance)"
   },
   {
    "name": "master",
    "query": "label_values(caos_etcd_server_has_leader, instance)"
   },
   {
    "name": "ingress",
    "query": "label_values(caos_probe{name!=\"httpingress\"}, name)"
   },
   {
    "name": "store",
    "query": "label_values(caos_cr_capacity_store_ryg, store)"
   },
   {
    "name": "pod",
    "query": "label_values(caos_cr_replicas_nodes_ryg, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Ingresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$ingress VIP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "ingress",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_probe{name=\"$ingress\",type=\"VIP\"})"
    }
   ]
  },
  {
   "title": "$ingress VIP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_probe{name=\"$ingress\",type=\"VIP\"})"
    }
   ]
  },
  {
   "title": "$ingress Upstream",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
   "repeat": "ingress",
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(caos_upstream_probe_ryg{name=\"$ingress\"})"
    }
   ]
  },
  {
   "title": "$ingress Upstream",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "avg(caos_upstream_probe_ryg{name=\"$ingress\"})"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "systemd $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_systemd_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "memory $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_memory_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "cpu $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_node_cpu_ryg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 22 },
   "repeat": "instance",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ready $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_k8s_node_ryg{node=\"$instance\"})"
    }
   ]
  },
  {
   "title": "etcd $master",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 26 },
   "repeat": "master",
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "caos_etcd_ryg{instance=\"$master\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "cluster cpu utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "caos_cluster_cpu_utilisation_5m"
    }
   ]
  },
  { "title": "ZITADEL Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CockroadDB Runtime Cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_cluster_ryg)"
    }
   ]
  },
  {
   "title": "CockroadDB Runtime Pod $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "repeat": "pod",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_runtime_pods_ryg{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Pod $pod",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "repeat": "pod",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_nodes_ryg{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Replicas Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "repeat": "store",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_replicas_stores_ryg{store=\"$store\"})"
    }
   ]
  },
  {
   "title": "CockroadDB Cluster Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_cluster_ryg)"
    }
   ]
  },
  {
   "title": "CockroadDB Disk Space Store $store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 59 },
   "repeat": "store",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(caos_cr_capacity_store_ryg{store=\"$store\"})"
    }
   ]
  }
 ]
}