{
 "title": "Health / Instance",
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance name",
    "query": "label_values(up{job=~\"caos_remote_(node-exporter|systemd-exporter)\"}, instance)"
   },
   {
    "name": "unit",
    "query": "label_values(caos_systemd_unit_active{instance=\"$instance\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 0 },
   "repeat": "unit",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "$unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_systemd_unit_active{name=~\"$unit\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max (time() - caos_node_boot_time_seconds{instance=\"$instance\"}) / 60 "
    }
   ]
  },
  {
   "title": "node ready",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_node_ready{ node=\"$instance\"}"
    }
   ]
  },
  {
   "title": "etcd is up and has a leader",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caos_etcd_server_has_leader_and_is_up{ instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "node CPU utilization 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "caos_node_cpu_utilisation_5m{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "node memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "caos_node_memory_utilisation{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "node disk utilization rootfs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "caos_node_disk_utilisation{instance=\"$instance\"} "
    }
   ]
  }
 ]
}