// Code generated by "gen-kindstubs -parentpath=github.com/caos/orbiter/internal/kinds/clusters -versions=v0 -kind=orbiter.caos.ch/KubernetesCluster from file gen.go"; DO NOT EDIT.

package kubernetes

import (
	"context"
	"fmt"

	"github.com/mitchellh/mapstructure"

	"github.com/caos/orbiter/internal/core/operator"

	"github.com/caos/orbiter/internal/kinds/clusters/kubernetes/adapter"
	"github.com/caos/orbiter/internal/kinds/clusters/kubernetes/model"
	v0builder "github.com/caos/orbiter/internal/kinds/clusters/kubernetes/model/v0"
)

type Version int

const (
	unknown Version = iota
	v0
)

type Kind struct {
	ID      string
	Kind    string
	Version string
	Spec    map[string]interface{}
	Deps    []map[string]interface{}
}

type assembler struct {
	path      []string
	overwrite func(map[string]interface{})
	builder   adapter.Builder
	built     adapter.Adapter
}

func New(configPath []string, overwrite func(map[string]interface{}), builder adapter.Builder) operator.Assembler {
	return &assembler{configPath, overwrite, builder, nil}
}

func (a *assembler) String() string { return "orbiter.caos.ch/KubernetesCluster" }
func (a *assembler) BuildContext() ([]string, func(map[string]interface{})) {
	return a.path, a.overwrite
}
func (a *assembler) Ensure(ctx context.Context, secrets *operator.Secrets, ensuredDependencies map[string]interface{}) (interface{}, error) {
	return a.built.Ensure(ctx, secrets, ensuredDependencies)
}
func (a *assembler) Build(serialized map[string]interface{}, nodeagentupdater operator.NodeAgentUpdater, secrets *operator.Secrets, dependant interface{}) (string, string, interface{}, map[string]operator.Assembler, error) {

	kind := &Kind{}
	if err := mapstructure.Decode(serialized, kind); err != nil {
		return "", "", nil, nil, err
	}

	if kind.Kind != "orbiter.caos.ch/KubernetesCluster" {
		return "", "", nil, nil, fmt.Errorf("Kind %s must be \"orbiter.caos.ch/KubernetesCluster\"", kind.Kind)
	}

	var spec model.UserSpec
	var subassemblersBuilder func(model.Config, []map[string]interface{}) (map[string]operator.Assembler, error)
	switch kind.Version {
	case v0.String():
		spec, subassemblersBuilder = v0builder.Build(kind.Spec, secrets, dependant)
	default:
		return "", "", nil, nil, fmt.Errorf("Unknown version %s", kind.Version)
	}

	cfg, adapter, err := a.builder.Build(spec, nodeagentupdater)
	if err != nil {
		return "", "", nil, nil, err
	}
	a.built = adapter

	if subassemblersBuilder == nil {
		return kind.Kind, kind.Version, cfg, nil, nil
	}

	subassemblers, err := subassemblersBuilder(cfg, kind.Deps)
	if err != nil {
		return "", "", nil, nil, err
	}

	return kind.Kind, kind.Version, cfg, subassemblers, nil
}
