kind: orbiter.caos.ch/Orbiter
version: v1
deps:
  t01:
    kind: orbiter.caos.ch/KubernetesCluster
    version: v1
    spec:
      versions:
        kubernetes: v1.17.0
        orbiter: v0.8.4
        boom: v0.6.1
      networking:
        dnsDomain: cluster.inhouse
        network: calico
        serviceCidr: 100.126.48.0/20
        podCidr: 100.126.32.0/20
      controlplane:
        updatesDisabled: false 
        provider: dc1
        nodes: 3
        pool: masters
      workers:
        workers:
          updatesDisabled: false
          provider: dc1
          nodes: 3
          pool: workers
    deps:
      dc1:
        kind: orbiter.caos.ch/StaticProvider
        version: v1
        spec:
          remoteuser: orbiter
          remotePublicKeyPath: /home/orbiter/.ssh/authorized_keys
          pools:
            masters:
            - id: master01
              hostname: master01
              externalIP: 10.73.244.115
              internalIP: 10.73.244.115
            - id: master02
              hostname: master02
              externalIP: 10.73.244.87
              internalIP: 10.73.244.87
            - id: master03
              hostname: master03
              externalIP: 10.73.244.102
              internalIP: 10.73.244.102
            workers:
            - id: worker01
              hostname: worker01
              externalIP: 10.73.244.107
              internalIP: 10.73.244.107
            - id: worker02
              hostname: worker02
              externalIP: 10.73.244.90
              internalIP: 10.73.244.90
            - id: worker03
              hostname: worker03
              externalIP: 10.73.244.109
              internalIP: 10.73.244.109
        deps:
          dynamic:
            kind: orbiter.caos.ch/DynamicLoadBalancer
            version: v1
            spec:
              masters:
              - ip: "10.73.244.69"
                transport:
                - name: kubelet
                  sourcePort: 10248
                  healthchecks:
                    protocol: http
                    path: /healthz
                    code: 200
                - name: kubeapi
                  sourcePort: 6443
                  healthchecks:
                    protocol: https
                    path: /healthz
                    code: 200
              workers:
              - ip: "10.73.244.70"
                transport:
                - name: httpsingress
                  sourcePort: 443
                  healthchecks:
                    protocol: https
                    path: /healthz
                    code: 200
                - name: httpingress
                  sourcePort: 80
                  healthchecks:
                    protocol: http
                    path: /healthz
                    code: 200

